### ISSUE TITLE
Logging Managment

### ISSUE THREAD

**Issue by amirsagiv83** [TechnionYP5777/Leonidas-FTW#116]
Find and create a logging method for our project. Make sure to Investigate Monitor class from the spartanizer of Eclipse

**Comment by yossigil** [comment]
@AnnaBel7 : add your partner, and pick the names of classes from telegram

**Comment by michalcohen** [comment]
Hey, I'm just reminding our requests: please add an API to the Logger enabling the print of regular strings to the log file and not only exception. There are many problems that occure only when the plugin is installed outside of the inner instance of intellij. For that reason the regular debugging is irrelevant.

**Comment by yossigil** [comment]
Take a look at class "monitor" and class "fault"

**Comment by RoeiRaz** [comment]
I tried using the logging facility that intellij provides (com.intellij.openapi.diagnostic.Logger), but it mixes up logs from our plugin and logs from intellij in a single file.
so I wrote a simple logging tool that outputs logs to a seperate log file (probably not the best solution, but i wanted to finally write some code 😄 )
take a look at the documentation at utils.logging, and for usage example take a look at SpartanizerAction.

**Comment by yossigil** [comment]
I remind you of fapi classes fault/monitor Let's try to combine them.

**Comment by michalcohen** [comment]
@RoeiRaz  @AnnaBel7  is it done?
