### ISSUE TITLE
Vacations

### ISSUE THREAD

**Issue by amirsagiv83** [TechnionYP5777/Leonidas-FTW#117]
After discussing the vacations subject we decided to open an issue in order to help us manage it better.
Each member must take 2 breaks, each a week long during the semester.
If you want to take a break, please make sure to announce about your break (in this issue and in the Telegram group) at least a week in advance.

Known vacations:
Oren - 23.4 - 29.4
Anna - 2.6 - 9.6
Michal - 3.4 - 9.4
Roey M. - 3.5 - 9.5
Sharon - 1.6 - 7.6

| Member | Week1  | Week2 | Week3  | Week4 | Week5  | Week6 | Week7  | Week8 | Week9  | Week10 | Week11  | Week12 | Week13  |
| ------------- | ------------- | ------------- | ------------- | ------------- | ------------- | ------------- | ------------- | ------------- | ------------- | ------------- | ------------- | ------------- | ------------- | 
| Oren  |   |   |  |  | 🎉  |   |  |  |  |  |  |  |  |
| Anna  |   |   |  |  |  |  |  |  |  | 🎉  |  | 🎉  |  |
| Michal  |   |   | 🎉  |  |  |  |  |  |  |  |  |  |  |
| Roey .M.  |   | 🎉  |  |  |  | 🎉  |  |  |  |  |  |  |  |
| Roei .R.  |   |   |  |  |  |  |  |  |  |  |  |  |  |
| Sharon  |   |   |  |  |  |  |  |  |  |  | 🎉  |  |  |
| Amir  |   |   |  |  |  |  | 🎉  |  |  |  |  |  |  |

@michalcohen @AnnaBel7 @orenafek @SharonKL @RoeiRaz @RoeyMaor

**Comment by yossigil** [comment]
Can we translate this to a table of weeks: Week 1,.. Week13
You know you can create tables in issues, right?

**Comment by amirsagiv83** [comment]
Done. Found it a little problematic to match dates to weeks, I tries my best, and I'll update it during the semester.

**Comment by yossigil** [comment]
+1:

**Comment by RoeyMaor** [comment]
i should be added on week 2 🌴

**Comment by amirsagiv83** [comment]
> i should be added on week 2 🌴

Done! 👍

**Comment by AnnaBel7** [comment]
I will be on vacation on 21.6-24.6, I think it is week 12.

**Comment by amirsagiv83** [comment]
> I will be on vacation on 21.6-24.6, I think it is week 12.

Done 👍

**Comment by RoeyMaor** [comment]
My second vacation will take place from 3.5 to 10.5

**Comment by amirsagiv83** [comment]
I'm adding myself to week 7.
