### ISSUE TITLE
Weekly Log For Anna Belozovsky

### ISSUE THREAD

**Issue by AnnaBel7** [TechnionYP5777/Leonidas-FTW#125]
New for semester 2, a fresh new page with a different name.
This is meant to help in monitoring everyone's assignments in the projects and what they are currently involved with.

Please use this as a weekly log from week 2 till the end of semester, both for you and me to see.
Log here past work that is finished, as well as current tasks you are doing.

Whenever possible, please include an issue number that you are working on, or that you have finished working on.
Best to use the bulleted list as a way to put things organized.

**Have a great semester!**

**Comment by AnnaBel7** [comment]
Weekly log for week 1 (19.3-25.3):
- [ ] Investigate parameterized tests #114 .
- [ ] Document Metafixture class from the original Spartanizer and understand how to use it.
- [ ] Create a wiki page describing our testing methods and the expected coverage.

**Comment by AnnaBel7** [comment]
Weekly log for week 2:
- Finished Investigating testing methods #114 
- Finished the testing wiki page #142 
- Analyzed assigned Spartanizer tippers and some of Roey Maor's tippers  #138

**Comment by yossigil** [comment]
I think this is a bit thin. You can do more. Compare to other weekly logs

**Comment by AnnaBel7** [comment]
Weekly log for week 3:
- Took part in a GUI team meeting
- Studied JavaFX from several wiki pages and tutorials
- Analyzed Michal's tippers and closed the issue #138 
- Fixed and polished [Install me wiki](https://github.com/TechnionYP5777/Leonidas-FTW/wiki/Install-Me) and [Join us wiki](https://github.com/TechnionYP5777/Leonidas-FTW/wiki/Join-US!) #141 
- Started working on the Playground GUI #160

**Comment by AnnaBel7** [comment]
Weekly log for week 4:
- Studied Swing from several tutorials
- Debugged Playground and converted it to Swing #160 
- Opened a discussion about moving to Swing instead of JavaFX #173 
- Helped debugging #171

**Comment by AnnaBel7** [comment]
Weekly log for week 5:
- Wrote a wiki page about using Swing #178 
- Polished and finished playground #160 
- Helped debugging "File not found" bug #193  
- Tested GenericPsiBlock #183 
- Tested GenericPsiExpression #184

**Comment by AnnaBel7** [comment]
Weekly log for week 6:
- Fixed whole file spartanization bug #206 
- Found a way to test GUI #200 
- Fixed travis so it allows gui testing
- Polished playground #160 
- Tested playground #207

**Comment by AnnaBel7** [comment]
Weekly log for week 7:
- Helped debugging #210 
- Worked on saving new tippers to files #214 
- Started working on TipperCreator functionality #211
