### ISSUE TITLE
Social warnings

### ISSUE THREAD

**Issue by RoeyMaor** [TechnionYP5777/Leonidas-FTW#131]
This issue shall remain open until the end of the semester

As part of the coding policy this semester, we aspire to minimize the amount of warnings in the code.
Therefore, we have embraced the idea of "social warnings".

All team members should try to avoid warnings. but, if for some reason (one couldn't find a way to prevent a warning / didn't have enough time to check for a warning-less solution etc) a team member needs to push code with new warnings, he/she shall comment here with the file name + location of warning(s). other team members should try and help by solving the warning(s) 🥇 and update here , or alternately, the creator of the warning will update that he/she had solved it.

![image](https://cloud.githubusercontent.com/assets/16507852/24322333/ed9ac1f8-1172-11e7-9ff5-0c068afb5faf.png)

**Comment by yossigil** [comment]
💯

**Comment by michalcohen** [comment]
The annoying "getText()" of PsiElement! it might return null and it is everywhere! :(

**Comment by yossigil** [comment]
make function text(x) that guards against it

**Comment by michalcohen** [comment]
Declaration redundancy: always apears for methods we've defined but yet implemented.
