### ISSUE TITLE
Analyzing Sprtanaizer Tippers

### ISSUE THREAD

**Issue by amirsagiv83** [TechnionYP5777/Leonidas-FTW#138]
As we discussed, we must analyze as many tips as we can to find those that can help us the most.
I'm giving each one of us a list of 5 tippers to analyze from the Eclipse Spartanizer. you should add your results here:
[link](https://docs.google.com/spreadsheets/d/104MH3Sw6a3_27Cb50p4p3CIwN5yxEkYY6boJIW9e37M/edit#gid=0)

Please keep the sheet as clear and clean as you can.
The last column (כפילויות) is to count how many times (in how many tippers) did you find the need for this specific method/identifier/etc...
Make sure you don't write the same thing twice with different names.

Tipper's list:

- [x] Sharon:
  - [x] CastToLong2Multiply1L
  - [x] TernaryBooleanLiteral
  - [x] IfEmptyThenEmptyElse
  - [x] InfixSubtractionZero
  - [x] InfixPlusEmptyString

- [x] Oren:

   - [x] IfLastInMethodThenEndingWithEmptyReturn
   - [x] IfLastInMethodElseEndingWithEmptyReturn
   - [x] IfCommandsSequencerNoElseSingletonSequencer
   - [x] IfPenultimateInMethodFollowedBySingleStatement
   - [x] IfLastInMethod

- [x] Roey .M.: - vacation-

    - [x] ArrayAccessAndIncrement

    - [x] FragmentInitializerIfAssignment

    - [x] FragmentInitializerIfUpdateAssignment

    - [x] FragmentInitializerReturnExpression

    - [x] FragmentInitializerInlineIntoNext

- [x] Roei .R.:
ContinueCoditinalInForEliminate
BlockBreakToReturnInfiniteFor
ForRedundantContinue
RemoveRedundantSwitchReturn
RemoveRedundantSwitchContinue

- [x] Anna:

TryBodyEmptyLeaveFinallyIfExists
TryBodyEmptyNoCatchesNoFinallyEliminate
TryFinallyEmptyRemove
FragmentInitializerDead
WhileEmptyBlockToEmptyStatement

- [x] Michal:

    - [x] InfixMultiplicationSort
    - [x] InfixPseudoAdditionSort
    - [x] InfixSubtractionSort
    - [x] InfixDivisonSortRest
    - [x] AnnotationSort

- [x] Amir:

IfReturnFooElseReturnBar
IfReturnNoElseReturn
IfAssignToFooElseAssignToFoo
IfThenFooBarElseFooBaz
IfBarFooElseBazFoo

Each group of tips are under a same category so some might be similar.
Some of the tips might be really hard to analyze and even not possible right now, so please write it down in the sheet and pick a different tip to analyze. Write it here in the comments.
Feel free to open a discussion in this issue about problems you run into.

Make sure to V your name when your'e done.

Good Luck! 😄

**Comment by orenafek** [comment]
:100:

**Comment by amirsagiv83** [comment]
Due to Roey's vacation this week, it is our responsibility to take care of his chores.
I'll start working on his tippers, and I'll mark those I'm done with.
Please take one or two if you have the time and mark them as done.

@orenafek @michalcohen @RoeiRaz @AnnaBel7 @SharonKL .

**Comment by amirsagiv83** [comment]
A lot of tips require an identifier presentation. For example if we want to write a template in which the object 'a' is important we need to create something that will represent it. We can't use methods as usual because in case of assignment to the object, we're stuck cause a method is not a legal L-value.
Any suggestions for a nice solution?

**Comment by SharonKL** [comment]
after some consideration regarding this issue yesterday (or shilshom) @michalcohen and I thought about introducing an array, called `ids` for example. This way you will be able to write, for example:

```Java
public void from() {
    ids[3] += 1;
}

public void to() {
    ids[3]++;
}
```

the type of this array can be an `int` or `double`, unless someone can think of a situation where these types are not going to be enough (in that case we can introduces `ids` of type `Object[]` and `numericIds` of type `double[]` for example).

**Comment by amirsagiv83** [comment]
and what about reprenting an array access to a specific array?

**Comment by SharonKL** [comment]
by specific array you mean we want to match the exact name of the array? then we have the same problem with methods

**Comment by yossigil** [comment]
You would have to study class `type` which gives the approximate type of variables and expressions

**Comment by orenafek** [comment]
I Can't find `FragmentInitializerInlineIntoNext`.
Where did this tipper come from ?
@amirsagiv83

**Comment by AnnaBel7** [comment]
@orenafek Seems like all the FragmentInitializer tippers (except one) were removed from the Spartanizer in the last few days, you can find them in earlier commits.

**Comment by yossigil** [comment]
No, they were renamed: Look for them in the toolbox, there are a zillion of these

**Comment by orenafek** [comment]
From what I've seen, `FragmentInitializerInlineIntoNext` is replaced with `LocalVariableIntializedInlineIntoNext`

and this tipper doesn't require a new basic block.
closing @RoeyMaor 's duties for this issues.

**Comment by yossigil** [comment]
Look for class Fragment, and check the various conditions in and its descendants

**Comment by AnnaBel7** [comment]
Done.
