### ISSUE TITLE
Starting GUI

### ISSUE THREAD

**Issue by amirsagiv83** [TechnionYP5777/Leonidas-FTW#139]
So, I decided to start and think about the GUI we will build this semester.
I think we should work with JavaFX, It's a great library full of options that don't exist in the standart Java GUI library.
Also, Sharon has some experience with this library from his previous project so he will be able to help us.

I started to get to know the library and work with it a little and I created a prototype for the Controller of the tippers.
This is only a GUI prototype and there is no logic behind (Yet!).
You're welcome to comment about it and tell me if you like it, or not, and how can we improve it.

![image](https://cloud.githubusercontent.com/assets/15860047/24549632/e9cfdf68-1622-11e7-9486-de74db3f5d4c.png)

I thought a good Idea will be to create a button in the IntelliJ menu that will open a Spartanizer Window with tabs. each tab represents a service of our plugin: Controlling notifications, changing tippers, etc...
this is a possible example to the controller that should supply the user the option to choose the tippers he wants to be notified on.

What do you think?

**Comment by AnnaBel7** [comment]
I think a window with tabs is a great idea.

In my opinion we should add an example of the tip in the control window (the one in the picture) as not all users will understand what exactly the tip does just by its name.

**Comment by amirsagiv83** [comment]
> In my opinion we should add an example of the tip in the control window (the one in the picture) as not all users will understand what exactly the tip does just by its name.

I agree, I thought of 2 options, adding an example for each tip, or, showing the Tipper description.

**Comment by orenafek** [comment]
> In my opinion we should add an example of the tip in the control window (the one in the picture) as not all users will understand what exactly the tip does just by its name.

I also agree, this looks great.
I think the use case should be:
Clicking a tipper -> the right side of the windows shows a short description and some examples.

also I believe it is best if the tippers are organized in categories, meaning one can also enable / disable a full category.

**Comment by amirsagiv83** [comment]
> also I believe it is best if the tippers are organized in categories, meaning one can also enable / disable a full category.

also great Idea, for now we can't really start building the back end of the GUI because of all the changes in the implementation but once it will be stable, we can start working on it.

**Comment by AnnaBel7** [comment]
We probably need a category to control the logging system in addition to the ones we already planned. @RoeiRaz

**Comment by amirsagiv83** [comment]
I Added a Prototype to the project. Will be updated soon

**Comment by amirsagiv83** [comment]
Following issues were opened after meeting with @TechnionYP5777/infra.
Closing the issue
