### ISSUE TITLE
Install Me wiki

### ISSUE THREAD

**Issue by yossigil** [TechnionYP5777/Leonidas-FTW#141]

**Comment by orenafek** [comment]
Done.
Copied from ReadMe.MD

**Comment by yossigil** [comment]
Please check that this works. Polish and finish

**Comment by AnnaBel7** [comment]
Both [Install me](https://github.com/TechnionYP5777/Leonidas-FTW/wiki/Install-Me) and [Join Us!](https://github.com/TechnionYP5777/Leonidas-FTW/wiki/Join-US!) wiki pages were updated
