### ISSUE TITLE
CI: call test coverage.

### ISSUE THREAD

**Issue by yossigil** [TechnionYP5777/Leonidas-FTW#157]

**Comment by SharonKL** [comment]
Followed several guides to integrate CodeCov with our project, but it will be hard to tell if I did something wrong or if Travis doesn't send the reports when the tests are still failing.

After we have fixed the builds, I will be able to finish the integration.

**Comment by SharonKL** [comment]
[![codecov](https://codecov.io/gh/TechnionYP5777/Leonidas-FTW/branch/master/graph/badge.svg)](https://codecov.io/gh/TechnionYP5777/Leonidas-FTW)

👍 

need to think we want to exclude some files/packages from the code coverage calculation, but this is for a new issue.

**Comment by yossigil** [comment]
:+1:
