### ISSUE TITLE
Read existing tippers when loading the plugin

### ISSUE THREAD

**Issue by SharonKL** [TechnionYP5777/Leonidas-FTW#164]
This issue refers to the static function `Toolbox.createLeonidasTipperBuilders2` which loads all the available tippers. The current way of doing this is by iterating through all the available source files in the `plugin.tippers.leonidas` package and saving them to temporary files in user's `TEMP` folder. These files are then used as the leonidas templates.

There are several problems that need to be fixed regarding this approach:

- [ ] Read only leonidas files from the temporary folder - the folder contains many temporary files, used by the OS and other programs, we care only about the leonidas files.
- [ ] Don't confuse between leonidas files from different activations of the plugin - each time the plugin is activated, these files are created, meaning that if we run the plugin multiple times, each tipper is created more than once. There are several possible solution as to how we will be able to read each tipper only once, one solution should be implemented.

**Comment by SharonKL** [comment]
Started working on this issue with @orenafek yesterday, but anyone can join if they want. The relevant functions (currently) are:

- `Toolbox.createLeonidasTipperBuilders2`
- `Utils.getSourceCode`

**Comment by orenafek** [comment]
Together with @RoeiRaz , working on a new angle:
Instead of writing into temporary files, steaming the content as a string directly
