### ISSUE TITLE
Spartanize current project

### ISSUE THREAD

**Issue by yossigil** [TechnionYP5777/Leonidas-FTW#168]
May be ad hoc.
@TechnionYP5777/infra

**Comment by amirsagiv83** [comment]
Do you mean spartanizing all through eclipse? or finding a way to spartanize through Intellij whenever we need?

**Comment by yossigil** [comment]
All through eclipse, as I said in telegram. The project currently does not load in eclipse

**Comment by amirsagiv83** [comment]
Is it possible to wait with it until we're done debugging?
As I understand the @TechnionYP5777/lingua  team is in the middle of implementing and debugging, and spartanizing the whole project might make things complicated...

**Comment by yossigil** [comment]
No, I mentioned this in telegram. I think the seven of you can manage this extra load.
