### ISSUE TITLE
Instructions (Wiki?) for eclipse loading

### ISSUE THREAD

**Issue by yossigil** [TechnionYP5777/Leonidas-FTW#170]

**Comment by amirsagiv83** [comment]
There is a plugin for eclipse you can download from the market - [Buildship Gradle Integration](https://marketplace.eclipse.org/content/buildship-gradle-integration)

It's supposed to help us import our gradle project.

**Comment by RoeyMaor** [comment]
I have ran into multiple problems, will update

**Comment by yossigil** [comment]
:+1:

**Comment by RoeyMaor** [comment]
The project can be imported and executed from eclipse!
I will write a wiki page explaining how to do so.

**Comment by RoeyMaor** [comment]
https://github.com/TechnionYP5777/Leonidas-FTW/wiki/Importing-the-project-to-eclipse
