### ISSUE TITLE
Using Swing instead of JavaFX

### ISSUE THREAD

**Issue by AnnaBel7** [TechnionYP5777/Leonidas-FTW#173]
From the experience I had this past two weeks, JavaFX is not so comfortable to use (and maybe doesn't work well with plugins in IntelliJ). When I started using Swing everything started working more smoothly.

In my opinion we should consider using Swing instead of JavaFX for our GUI in the project.

What do you think?
@TechnionYP5777/infra

**Comment by amirsagiv83** [comment]
Can you add a link to where you saw JavaFX might create problems?

**Comment by AnnaBel7** [comment]
I've seen a lot of people complaining about similar problems, for example [here](https://intellij-support.jetbrains.com/hc/en-us/community/posts/206760275-Does-Intellij-SDK-work-with-JavaFX-) and [here](https://intellij-support.jetbrains.com/hc/en-us/community/posts/206760285-Setup-of-a-plugin-to-use-JavaFX-for-its-GUI-Sw?page=1#community_comment_206106495).
I haven't found newer information about it and the suggested solution didn't work for me.

**Comment by michalcohen** [comment]
I think as well that moving to swing will spair us many problems. More over, The GUI I've written was already written in Swing

**Comment by amirsagiv83** [comment]
Swing it is!
