### ISSUE TITLE
Tests for Toolbox

### ISSUE THREAD

**Issue by michalcohen** [TechnionYP5777/Leonidas-FTW#191]

**Comment by michalcohen** [comment]
Have you managed to create an instance of project while testing? The instance of the Toolbox is created by "ApplicationManager.getApplication().getComponent" and that can't be changed...
@amirsagiv83

**Comment by amirsagiv83** [comment]
Done.

**Comment by michalcohen** [comment]
So terribly sorry, but our latest changes caused almost all of the test not to pass :S
If you need any help correcting this, just say! @amirsagiv83

**Comment by amirsagiv83** [comment]
Fun Time!

**Comment by orenafek** [comment]
no.

**Comment by amirsagiv83** [comment]
All the tests are passing on my computer...
