### ISSUE TITLE
Find a way to automatically test GUI

### ISSUE THREAD

**Issue by michalcohen** [TechnionYP5777/Leonidas-FTW#200]
@AnnaBel7  @amirsagiv83 do you know any convenient ways to do this? Who do you think this issue is most relevant for?

**Comment by AnnaBel7** [comment]
I think it's more relevant for me as I studied testing methods at the beginning of the semester

**Comment by michalcohen** [comment]
Cool! Maybe "Swinger" can help https://www.youtube.com/v/YCLsXka_QvA

**Comment by michalcohen** [comment]
Have you managed to fix the problem with HeadlessException?

**Comment by AnnaBel7** [comment]
Not yet, I'm working on it now

**Comment by AnnaBel7** [comment]
Travis works now with gui testing. We can start testing our gui!
