### ISSUE TITLE
not replacing always true statement with removing the if

### ISSUE THREAD

**Issue by Kolikant** [TechnionYP5777/Leonidas-FTW#235]
I made exceptionally stupid code 

![image](https://user-images.githubusercontent.com/23051198/27768905-9350b362-5f27-11e7-83e4-76036a63f0a3.png)

however, even though the statement is always true, spartanization left it in
![image](https://user-images.githubusercontent.com/23051198/27768911-af57490e-5f27-11e7-970b-5e252eabd6ea.png)

**Comment by SharonKL** [comment]
We don't have a tipper for this particular situation. IntelliJ already has a built in inspection that checks for this and is enabled by default so we decided to leave this out.
