### ISSUE TITLE
I am unable to understand any of the options

### ISSUE THREAD

**Issue by Kolikant** [TechnionYP5777/Leonidas-FTW#237]
![image](https://user-images.githubusercontent.com/23051198/27768991-348d180a-5f29-11e7-9575-ff1f332a97c9.png)

the names don't mean anything to me and there isn't an explanation on them, the only way to understand what each one does is through trial and error and that's just not nice :(

**Comment by RoeyMaor** [comment]
Please install the version from the relevant repo #240
